language: objective-c
xcode_project: POCContinuousIntegrationTravisTest/POCContinuousIntegrationTravisTest.xcodeproj/ # path to your xcodeproj folder
xcode_scheme: POCContinuousIntegrationTravisTest

